<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\BoltUpdateTool.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-arm64;win-x86</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bolt.Protocol\Bolt.Protocol.csproj" />
    <ProjectReference Include="..\Bolt.WindowsHid\Bolt.WindowsHid.csproj" />
    <Resource Include="Assets\BoltUpdateTool.ico" />
  </ItemGroup>
</Project>
